### ISSUE TITLE
Possible bug/Interaction with Quest Tracker Addon

### ISSUE THREAD

**Issue by lilrichy** [lilrichy/ListTracker#3]
Possible add-on interaction bug with Quest Tracker. Pet battles hide interface when List Tracker Addon is enabled.

**Comment by lilrichy** [comment]
https://www.curseforge.com/wow/addons/list-tracker?comment=13

**Comment by ciphersimian** [comment]
I'm also seeing an issue with kaliels-tracker which is a Quest Tracker replacement.

This is a very simple addon that doesn't seem like it should interact with the Quest Tracker at all.  Can you try to eliminate whatever dependency/interaction it has to fix this issue?

https://www.curseforge.com/wow/addons/kaliels-tracker/issues/519

**Comment by lilrichy** [comment]
This should be fixed in version 1.1.11

**Comment by ciphersimian** [comment]
Awesome, thanks for the quick turnaround.  That solved the issue and I had no problems tonight!

**Comment by lilrichy** [comment]
Glad it worked! :D
